#!/bin/bash

source ~/.config/profile/profile-colors.sh
source ~/.config/profile/profile-aliases.sh
source ~/.config/profile/profile-dev.sh
source ~/.config/profile/profile-env.sh
source ~/.config/profile/profile-utilities.sh

if [ "$1" != "quiet" ] ; then
    fastfetch
    gitchk
fi
