# Generated by nwg-displays on 2025-12-05 at 23:07:39. Do not edit manually.
hl.monitor({
    output = "desc:Dell Inc. DELL P2418HZm P0JNT19U5N8B",
    mode = "1920x1080@60.0",
    position = "1243x725",
    scale = "1.0",
})

hl.monitor({
    output = "desc:Dell Inc. AW3425DWM JFQ4444",
    mode = "3440x1440@59.97",
    position = "512x1805",
    scale = "1.0",
})
