[config]

[templates.hyprlandLua]
input_path = '~/.config/matugen/templates/hyprland-colors.lua'
output_path = '~/.config/hypr/colors.lua'
post_hook = 'hyprctl reload'

[templates.hyprlock]
input_path = '~/.config/matugen/templates/hyprlock.conf'
output_path = '~/.config/hypr/hyprlock.conf'

[templates.waybar]
input_path = '~/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
#post_hook = 'pkill -SIGUSR2 waybar'
post_hook = 'pkill waybar && waybar &'

[templates.nvim]
input_path = '~/.config/matugen/templates/nvim-colors.json'
output_path = '~/.config/nvim/colors.json'

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-color.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'

[templates.openrgb]
input_path = '~/.config/matugen/templates/openrgb_accent.json'
output_path = '~/.config/OpenRGB/colors.json'
post_hook = 'python ~/.config/matugen/post-hook-scripts/openrgb_setup.py'

[templates.emacs]
input_path = "~/.config/matugen/templates/emacs.el"
output_path = "~/.config/doom/themes/doom-matugen-theme.el"
post_hook = "~/.config/matugen/post-hook-scripts/emacs-reload-theme.sh"

# configs from https://github.com/InioX/matugen-themes
[templates.firefox-website-colors]
input_path = "~/.config/matugen/templates/firefox-website-colors.css"
output_path = "~/.mozilla/firefox/041c6668.default-release/chrome/colors.css"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = '~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh'

[templates.vscode-raw]
input_path = './templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = './templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

#[templates.steam]
#input_path = './templates/steam.css'
#output_path = '~/.config/AdwSteamGtk/custom.css'
#post_hook =  'adwaita-steam-gtk -i'

[templates.vesktop]
input_path = './templates/discord.css'
output_path = '~/.config/vesktop/themes/midnight-discord.css'
